### ISSUE TITLE
MIT Licence

### ISSUE THREAD

**Issue by raubv0gel** [BrunoMNDantas/TPL4J#35]
Is there any chance that this great library will be published under MIT licence?

**Comment by BrunoMNDantas** [comment]
> Is there any chance that this great library will be published under MIT licence?

Hi raubvogel,

Thanks for the sugestion. 
When I started this project I selected the first license github suggested. 
I've just changed the license's file to MIT version. Changing the license file is enough?

**Comment by raubv0gel** [comment]
@BrunoMNDantas, you are great! Thank you very much!

Yes, I believe change the license file is enough.
